version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8001'
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     DJANGO_SETTINGS_MODULE: main.settings
   command: 'python -u consumer.py'
   depends_on:
     - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
